version: '3.8'
services:

  open_webui:
    build:
      context: open_webui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - relational_database
      - sergeant_service
    environment:
      - GOOGLE_PSE_API_KEY=${GOOGLE_PSE_API_KEY}
      - GOOGLE_PSE_ENGINE_ID=${GOOGLE_PSE_ENGINE_ID}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${MICROSOFT_CLIENT_TENANT_ID}
      - RAG_OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE_URL=http://sergeant_service:8000
      - DATABASE_URL=postgresql://openwebui:unsecuredpassword@relational_database:5432/openwebui

  relational_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: openwebui
      POSTGRES_USER: openwebui
      POSTGRES_PASSWORD: unsecuredpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sergeant_service:
    build:
      context: sergeant_service
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}


volumes:
  postgres_data:
