version: '3.8'
services:

  open_webui:
    image: ghcr.io/lieutenant-ecosystem/open_webui:${ENVIRONMENT}
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - relational_database
      - sergeant_service
    environment:
      - GOOGLE_PSE_API_KEY=${GOOGLE_PSE_API_KEY}
      - GOOGLE_PSE_ENGINE_ID=${GOOGLE_PSE_ENGINE_ID}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${MICROSOFT_CLIENT_TENANT_ID}
      - RAG_OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE_URL=http://sergeant_service:8000
      - DATABASE_URL=postgresql://openwebui:unsecuredpassword@relational_database:5432/openwebui
      - ENV=dev
    networks:
      - lieutenant-intranet

  relational_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: openwebui
      POSTGRES_USER: openwebui
      POSTGRES_PASSWORD: unsecuredpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lieutenant-intranet

  sergeant_service:
    image: ghcr.io/lieutenant-ecosystem/sergeant_service:${ENVIRONMENT}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PPLX_API_KEY=${PPLX_API_KEY}
    networks:
      - lieutenant-intranet

  gateway:
    image: ghcr.io/lieutenant-ecosystem/gateway:${ENVIRONMENT}
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
    networks:
      - lieutenant-intranet

volumes:
  postgres_data:

networks:
  lieutenant-intranet:
    driver: bridge
