apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ghcr.io/lieutenant-ecosystem/gateway:dev
          imagePullPolicy: Always
          env:
            - name: CLOUDFLARE_TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: CLOUDFLARE_TUNNEL_TOKEN
            - name: SSH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: SSH_USERNAME
            - name: SSH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: SSH_PUBLIC_KEY
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-network-policy
spec:
  podSelector:
    matchLabels:
      app: gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: lieutenant
        - podSelector:
            matchLabels:
              app: postgres
        - podSelector:
            matchLabels:
              app: gateway
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: lieutenant
        - podSelector:
            matchLabels:
              app: postgres
        - podSelector:
            matchLabels:
              app: gateway
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0  # Allow egress to the internet