apiVersion: apps/v1
kind: Deployment
metadata:
  name: lieutenant
  labels:
    app: lieutenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lieutenant
  template:
    metadata:
      labels:
        app: lieutenant
        role: lieutenant
    spec:
      hostNetwork: true  # Joins the Kubernetes network with the host's network
      containers:
        - name: open-webui
          image: localhost:32000/open_webui:local
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: "DEV"
            - name: OPENAI_API_BASE_URL
              value: "http://localhost:8000"
            - name: RAG_OPENAI_API_BASE_URL
              value: "http://localhost:8001"
            - name: AUDIO_STT_ENGINE
              value: "openai"
            - name: AUDIO_TTS_ENGINE
              value: "openai"
            - name: AUDIO_STT_MODEL
              value: "whisper-1"
            - name: RAG_EMBEDDING_ENGINE
              value: "openai"
            - name: ENABLE_EVALUATION_ARENA_MODELS
              value: "False"
            - name: RAG_EMBEDDING_MODEL
              value: "text-embedding-3-small"
            - name: ENABLE_RAG_WEB_SEARCH
              value: "False"
            - name: ENABLE_OAUTH_SIGNUP
              value: "True"
            - name: ENABLE_LOGIN_FORM
              value: "False"
            - name: ENABLE_OLLAMA_API
              value: "False"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: DATABASE_URL
                  optional: true
            - name: MICROSOFT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: MICROSOFT_CLIENT_ID
                  optional: true
            - name: MICROSOFT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: MICROSOFT_CLIENT_SECRET
                  optional: true
            - name: MICROSOFT_CLIENT_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: MICROSOFT_CLIENT_TENANT_ID
                  optional: true
            - name: AUDIO_TTS_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_API_KEY
            - name: AUDIO_STT_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_API_KEY
            - name: RAG_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_API_KEY
          ports:
            - containerPort: 8080

        - name: sergeant-service
          image: localhost:32000/sergeant_service:local
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "DEV"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_COMPATIBLE_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_COMPATIBLE_API_BASE_URL
            - name: OPENAI_COMPATIBLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_COMPATIBLE_API_KEY
            - name: VECTOR_EMBEDDING_SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: VECTOR_EMBEDDING_SERVICE_DATABASE_URL
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: SENTRY_DSN

        - name: vector-embedding-service
          image: localhost:32000/vector_embedding_service:local
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: ENVIRONMENT
              value: "DEV"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_COMPATIBLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_COMPATIBLE_API_KEY
            - name: OPENAI_COMPATIBLE_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: OPENAI_COMPATIBLE_API_BASE_URL
            - name: VECTOR_EMBEDDING_SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: VECTOR_EMBEDDING_SERVICE_DATABASE_URL
            - name: VECTOR_EMBEDDING_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: VECTOR_EMBEDDING_BASE_URL
                  optional: true
            - name: VECTOR_EMBEDDING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: VECTOR_EMBEDDING_API_KEY
                  optional: true
            - name: VECTOR_EMBEDDING_SERVICE_DEFAULT_MODEL
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: VECTOR_EMBEDDING_SERVICE_DEFAULT_MODEL
                  optional: true
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: lieutenant-secrets
                  key: SENTRY_DSN

        - name: intelligence-service
          image: localhost:32000/intelligence_service:local
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: ENVIRONMENT
              value: "DEV"

---

apiVersion: v1
kind: Service
metadata:
  name: lieutenant-service
  labels:
    app: lieutenant
spec:
  selector:
    app: lieutenant
  ports:
    - name: open-webui
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: sergeant-service
      protocol: TCP
      port: 81
      targetPort: 8000
    - name: vector-embedding-service
      protocol: TCP
      port: 82
      targetPort: 8001
    - name: intelligence-service
      protocol: TCP
      port: 83
      targetPort: 8002

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lieutenant-network-policy
spec:
  podSelector:
    matchLabels:
      app: lieutenant
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: lieutenant
        - podSelector:
            matchLabels:
              app: postgres
        - podSelector:
            matchLabels:
              app: gateway
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: lieutenant
        - podSelector:
            matchLabels:
              app: postgres
        - podSelector:
            matchLabels:
              app: gateway
