FROM ghcr.io/open-webui/open-webui:latest

#   Open WebUI specific configurations (view https://docs.openwebui.com/getting-started/env-configuration/)
ENV WEBUI_NAME="Open WebUI"
ENV ENABLE_OAUTH_SIGNUP=true
ENV ENABLE_OLLAMA_API=false
ENV ENABLE_LOGIN_FORM=false
ENV ENABLE_RAG_WEB_SEARCH=true
ENV ENABLE_SEARCH_QUERY=true
ENV RAG_WEB_SEARCH_ENGINE=google_pse
ENV RAG_WEB_SEARCH_RESULT_COUNT=5
ENV RAG_EMBEDDING_ENGINE=openai
ENV RAG_EMBEDDING_MODEL=text-embedding-3-small
ENV OPENAI_API_KEY=unsecured